# Generated by Django 5.0.1 on 2024-02-23 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст объявления')),
                ('category', models.CharField(choices=[('TN', 'Танки'), ('HL', 'Хилы'), ('DD', 'ДД'), ('MA', 'Торговцы'), ('GM', 'Гилдмастеры'), ('GI', 'Квестгиверы'), ('BS', 'Кузнецы'), ('TA', 'Кожевники'), ('PB', 'Зельевары'), ('SM', 'Мастера заклинаний')], default='tanks', max_length=2, verbose_name='Категория')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('upload', models.FileField(blank=True, help_text='Загрузите файл', upload_to='uploads/', verbose_name='Загрузка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание')),
                ('status', models.BooleanField(default=False, verbose_name='Статус отклика')),
                ('adComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.announcement', verbose_name='Комментарий')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Откликнувшийся')),
            ],
        ),
    ]
